Feature: Add entry logic for push notifications
informatyzacja/events-app pull request #9
Opened 2023-03-09 17:09 UTC by DocentSzachista

For now its a draft of push notifications. I haven't tested it yet.

2023-03-10 14:40 UTC, Omikorin approved these changes

2023-03-14 15:27 UTC, Rei-x requested changes

2023-03-14 15:27 UTC, Rei-x commented on apps/expo/src/hooks/useSubscribedEvents.js
> +    });
dlaczego użyłeś then? może z tego wyniknąć jakieś dziwne race condition

zrób po prostu
```js
const subscribe = async (event) => {
  const id = await scheduleNotification(event);
  ...
}

2023-03-14 15:27 UTC, Rei-x commented on apps/expo/src/hooks/useSubscribedEvents.js
> +  await Notifications.cancelScheduledNotificationAsync(event.notificationId);
daj tu returna po prostu i możesz nawet asynca wywalić

2023-04-05 17:13 UTC, Rei-x approved these changes

2023-04-05 17:13 UTC, merged